Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
### DB vm  ####
  config.vm.define "db01" do |db01|
    db01.vm.box = "generic/centos9s"
    #db01.vm.box_version = "9.0.45"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.55"
    db01.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
   end

  end
  
### Memcache vm  #### 
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "generic/centos9s"
    #mc01.vm.box_version = "9.0.45"
    mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", ip: "192.168.56.54"
    mc01.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
   end
  end
  
### RabbitMQ vm  ####
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "generic/centos9s"
    #rmq01.vm.box_version = "9.0.45"
    rmq01.vm.hostname = "rmq01"
    rmq01.vm.network "private_network", ip: "192.168.56.53"
    rmq01.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
   end
  end
  
### tomcat vm ###
   config.vm.define "app01" do |app01|
    app01.vm.box = "generic/centos9s"
    #app01.vm.box_version = "9.0.45"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.56.52"
    app01.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
   end
   end
   
  
### Nginx VM ###
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/jammy64"
    web01.vm.hostname = "web01"
  web01.vm.network "private_network", ip: "192.168.56.51"
  web01.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "2048"
   end
end
  
end
